linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - exportloopref
    - gocyclo
    - dupl
    - goconst
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - gosec
  disable:
    - structcheck
    - varcheck
    - deadcode
    - ifshort

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - unparam

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
