version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - dupl
    - goconst
    - gocyclo
    - gosec
    - misspell
    - unconvert
  disable:
    - nakedret
    - prealloc
    - unparam
  settings:
    dupl:
      threshold: 120
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 20
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocyclo
          - gosec
          - govet
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
