linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment  # Disable struct field alignment checks
  gocyclo:
    min-complexity: 20  # Increase complexity threshold
  dupl:
    threshold: 120  # Increase duplication threshold
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocyclo
    - dupl
    - goconst
    - misspell
    - unconvert
    - gosec
  disable:
    - structcheck  # Deprecated
    - varcheck  # Deprecated
    - deadcode  # Deprecated
    - ifshort  # Deprecated
    - exportloopref  # Deprecated (Go 1.22+)
    - unparam  # Too strict for this codebase
    - nakedret  # Acceptable for small functions
    - prealloc  # Optimization not critical

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocyclo
        - govet

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
